INSERT INTO SessionsSpeakers VALUES (1, 1)
INSERT INTO SessionsSpeakers VALUES (2, 1)
INSERT INTO SessionsSpeakers VALUES (3, 1)
INSERT INTO SessionsSpeakers VALUES (4, 2)
INSERT INTO SessionsSpeakers VALUES (5, 2)