CREATE TABLE [dbo].[Speakers]
(
	[Id] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
	[FirstName] NVARCHAR(128) NOT NULL,
	[LastName] NVARCHAR(128) NULL,
	[TwitterProfile] NVARCHAR(256) NULL,
	[LinkedinProfile] NVARCHAR(256) NULL,
	[Website] NVARCHAR(256) NULL,
	[Biography] NVARCHAR(MAX) NOT NULL,
	[Image] NVARCHAR(256) NOT NULL,
	[City] NVARCHAR(256) NOT NULL,
	[Country] NVARCHAR(256) NOT NULL,
	CONSTRAINT [PK_Speaker] PRIMARY KEY CLUSTERED ([Id] ASC)
)
